Repository phybros/servertap, pull requests merged in 2020-11, with the labels that each got.

#38 Added webhooks
  src/main/java/io/servertap/PluginEntrypoint.java
  src/main/java/io/servertap/RegisteredWebhook.java
  src/main/java/io/servertap/WebhookEventListener.java
  src/main/java/io/servertap/api/v1/models/events/PlayerChatWebhookEvent.java
  src/main/java/io/servertap/api/v1/models/events/PlayerDeathWebhookEvent.java
  src/main/java/io/servertap/api/v1/models/events/PlayerJoinWebhookEvent.java
  src/main/java/io/servertap/api/v1/models/events/PlayerKickWebhookEvent.java
  src/main/java/io/servertap/api/v1/models/events/PlayerQuitWebhookEvent.java
  src/main/java/io/servertap/api/v1/models/events/WebhookEvent.java
Labels: feature

#45 Added key authentication before each call
  .gitignore
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/servertap/v16/.suo
  .vs/slnx.sqlite
  src/main/java/io/servertap/PluginEntrypoint.java
  src/main/resources/config.yml
Labels: feature

#49 Moved Broadcast under /chat and added tell command
  src/main/java/io/servertap/Constants.java
  src/main/java/io/servertap/PluginEntrypoint.java
  src/main/java/io/servertap/api/v1/ServerApi.java
Labels: enhancement

#52 Fixed error message, to better reflect the issue
  src/main/java/io/servertap/Constants.java
Labels: bug
